on:
  push:
    tags:
      - "pdf-*-v*.*"
      # pdf-[target]-v[major].[edit]
      # e.g. pdf-coop-v1.3

permissions:
  contents: write

jobs:
  generate_pdf_job:
    runs-on: ubuntu-latest
    name: A job to generate a pdf
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: pip install --no-cache-dir rendercv[full]

      - name: Render CV
        run: rendercv render Damien_Hodsall_CV.yaml

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          files: rendercv_output/Damien_Hodsall_CV.pdf
